import type { App, Template, MockUser } from './types';

export const MOCK_USER: MockUser = {
  id: 'mock_user',
  name: 'Alex',
  email: 'alex@example.com',
  avatarIndex: 0,
};

// Thumbnail keys map to color swatches rendered in AppCard
export const THUMBNAIL_COLORS: Record<string, string> = {
  thumb_blue:    '#3B6FE8',
  thumb_teal:    '#0D9488',
  thumb_violet:  '#7C3AED',
  thumb_amber:   '#D97706',
  thumb_rose:    '#E11D48',
  thumb_emerald: '#059669',
  thumb_sky:     '#0284C7',
  thumb_indigo:  '#4338CA',
};

export const MOCK_DRAFT_APPS: App[] = [
  {
    id: 'app_001',
    name: 'Product Description Generator',
    description: 'Turn a product name into a compelling marketing description.',
    status: 'draft',
    thumbnail: 'thumb_blue',
    ownerId: 'mock_user',
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-06-12T14:30:00Z',
    widgets: [],
  },
  {
    id: 'app_002',
    name: 'Social Caption Writer',
    description: 'Generate captions for Instagram, LinkedIn, and Twitter.',
    status: 'draft',
    thumbnail: 'thumb_violet',
    ownerId: 'mock_user',
    createdAt: '2026-05-20T11:00:00Z',
    updatedAt: '2026-06-14T10:15:00Z',
    widgets: [],
  },
  {
    id: 'app_003',
    name: 'Lead Qualifier',
    description: 'Ask a few questions and score inbound leads automatically.',
    status: 'draft',
    thumbnail: 'thumb_teal',
    ownerId: 'mock_user',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-15T16:00:00Z',
    widgets: [],
  },
  {
    id: 'app_004',
    name: 'FAQ Chatbot',
    description: 'A simple chat interface powered by your documentation.',
    status: 'draft',
    thumbnail: 'thumb_amber',
    ownerId: 'mock_user',
    createdAt: '2026-06-08T09:30:00Z',
    updatedAt: '2026-06-15T09:45:00Z',
    widgets: [],
  },
  {
    id: 'app_005',
    name: 'Untitled App',
    description: '',
    status: 'draft',
    thumbnail: 'thumb_rose',
    ownerId: 'mock_user',
    createdAt: '2026-06-16T08:00:00Z',
    updatedAt: '2026-06-16T08:00:00Z',
    widgets: [],
  },
];

export const MOCK_PUBLISHED_APPS: App[] = [
  {
    id: 'app_pub_001',
    name: 'Email Subject Line Generator',
    description: 'Write high-performing subject lines for any email campaign.',
    status: 'published',
    thumbnail: 'thumb_emerald',
    ownerId: 'mock_user',
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-04-28T12:00:00Z',
    publishedAt: '2026-04-28T13:00:00Z',
    widgets: [],
  },
  {
    id: 'app_pub_002',
    name: 'Internal Wiki Assistant',
    description: 'Ask questions, get answers pulled from your team wiki.',
    status: 'published',
    thumbnail: 'thumb_sky',
    ownerId: 'mock_user',
    createdAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-05-10T14:00:00Z',
    publishedAt: '2026-05-10T15:00:00Z',
    widgets: [],
  },
  {
    id: 'app_pub_003',
    name: 'Job Description Writer',
    description: 'Draft clear, inclusive job descriptions in under a minute.',
    status: 'published',
    thumbnail: 'thumb_indigo',
    ownerId: 'mock_user',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-20T10:00:00Z',
    publishedAt: '2026-05-20T11:00:00Z',
    widgets: [],
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tmpl_001',
    name: 'FAQ Chatbot',
    description: 'A ready-to-use chat interface that answers common support questions instantly.',
    author: 'Forge Team',
    authorAvatar: '0',
    thumbnail: 'thumb_violet',
    accentColor: '#4C1D95',
    category: 'Support',
    rating: 4.8,
    cloneCount: 1240,
    publishedAt: '2026-04-01T00:00:00Z',
    featured: true,
  },
  {
    id: 'tmpl_002',
    name: 'Product Description Generator',
    description: 'Input a product name and get a polished marketing description instantly.',
    author: 'Forge Team',
    authorAvatar: '1',
    thumbnail: 'thumb_amber',
    accentColor: '#78350F',
    category: 'Marketing',
    rating: 4.7,
    cloneCount: 980,
    publishedAt: '2026-04-05T00:00:00Z',
    featured: true,
  },
  {
    id: 'tmpl_003',
    name: 'Social Caption Writer',
    description: 'Generate platform-specific captions for Instagram, LinkedIn, and X.',
    author: 'Forge Team',
    authorAvatar: '2',
    thumbnail: 'thumb_rose',
    accentColor: '#881337',
    category: 'Marketing',
    rating: 4.6,
    cloneCount: 760,
    publishedAt: '2026-04-10T00:00:00Z',
    featured: true,
  },
  {
    id: 'tmpl_004',
    name: 'Lead Qualifier',
    description: 'Ask prospects a few questions and score inbound leads automatically.',
    author: 'Forge Team',
    authorAvatar: '0',
    thumbnail: 'thumb_blue',
    accentColor: '#1E3A5F',
    category: 'Sales',
    rating: 4.5,
    cloneCount: 540,
    publishedAt: '2026-04-15T00:00:00Z',
    featured: false,
  },
  {
    id: 'tmpl_005',
    name: 'Image Prompt Generator',
    description: 'Describe a scene and get optimised prompts for Midjourney or DALL·E.',
    author: 'Forge Team',
    authorAvatar: '1',
    thumbnail: 'thumb_teal',
    accentColor: '#134E4A',
    category: 'Creative',
    rating: 4.9,
    cloneCount: 2100,
    publishedAt: '2026-03-20T00:00:00Z',
    featured: false,
  },
  {
    id: 'tmpl_006',
    name: 'Study Assistant',
    description: 'A Socratic tutor that explains concepts and quizzes you at your own pace.',
    author: 'Forge Team',
    authorAvatar: '2',
    thumbnail: 'thumb_indigo',
    accentColor: '#312E81',
    category: 'Education',
    rating: 4.4,
    cloneCount: 320,
    publishedAt: '2026-05-01T00:00:00Z',
    featured: false,
  },
];
